# Dockerfile-server
FROM node:18

WORKDIR /app

# Copy environment file
COPY server/.env .env

# Copy the rest of the project files
COPY server/package*.json ./
COPY server/ ./

# Install dependencies and build TypeScript
RUN npm install
RUN npm run build

# Expose API port
EXPOSE 5000

# Start the server
CMD ["node", "dist/index.js"]
