# Dockerfile-client
FROM node:18 AS builder

WORKDIR /app

# Copy environment file
COPY client/.env .env

# Copy project files
COPY client/package*.json ./
COPY client/ ./

# Install dependencies and build
RUN npm install
RUN npm run build

# Serve using NGINX
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
